name: custom_poll
description: "A Customizable Polls for Flutter. Simple, easy to use and highly customizable."
version: 0.0.1
homepage: "https://github.com/SwanFlutter/custom_poll.git"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  
  flutter:
    sdk: flutter
  intl: ^0.20.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:


